version: "v1.0"

# 환율 기준
# 1유로 = 1달러
# 1달러 = 1,500원

# 트럭: 현대 포터2
# 공식 문서: https://www.hyundai.com/kr/ko/vehicles/porter2-special/20my/specifications.html

# 로봇: Starship Technology
# 공식 문서: https://www.wevolver.com/specs/starship-technologies-starship-robot
# 사이트: https://www.starship.xyz/robot

# 한국전력공사: https://online.kepco.co.kr/PRM004D00

# Changing geometry or either speed requires preprocessing again.
geometry:
  metric: manhattan
  scaling_factor: 1.0
  path_convention: average
  n_samples: 100

# Truck count is resolved from the required experiment size.
fleet:
  n_trucks:
    5: 2
    10: 2
    20: 2
    50: 4
    100: 7
    150: 10
    200: 12
    250: 15
    300: 17
  n_robots_per_truck: 2

truck:
  speed_kmh: 27.0 # 한국교통연구원 https://viewt.ktdb.go.kr/cong/map/TableMove_Zeke.do 참고.
  capacity: 150 # 현대 포터2 공식 문서 참고. 화물실 부피 7.47 m³ / 1박스 0.05 m³ 기준으로 계산.
  range_km: 550.0 # 현대 포터2 공식 문서 참고. 연료탱크 용량 65 L * 연비 8.6 km/L 기준으로 계산.
  fixed_cost: 31.48 # 7.87 * 4.0. 한국교통연구원 참고. 1시간 기준으로 4시간 운행 비용으로 계산. 
  fuel_cost_per_min: 0.052 # 현대 포터2 공식 문서 + 한국교통연구원 참고. 평균 속도 27.0 km/h * 연비 (1/8.6 km/L) * 경유 단가 1$/L 기준으로 계산. -> 3.1395 $/h -> 0.052 $/min
  env_cost_per_min: 0.0185 # 현대 포터2 공식 문서 + Rennert(2022) 논문 참고. 평균 속도 27.0 km/h * CO2 배출량 222g/km -> ~ 6.0 kg/h -> 0.1 kg/min -> 0.0001 tCO2/min. 0.0001 tCO2/min * 185 $/tCO2 -> 0.0185 $/min
  service_time_min: 5.0 # 유선님 논문(2025) 참고.

robot:
  speed_kmh: 6.0 # Starship Technology 문서 참고.
  capacity: 3 # Starship Technology 문서 참고. 화물실 부피 0.0435 m³ / 1박스 0.015 m³ 기준으로 계산.
  range_km: 40.0 # Starship Technology 사이트 참고.
  fixed_cost: 2.0 # 0.5 * 4.0. Ostermeier(2025) 논문 참고. 1시간 기준으로 4시간 운행 비용으로 계산. 
  fuel_cost_per_min: 0.00017 # Starship Technology 문서 + 한국전력공사 참고. 배터리 용량 1.26kWh / 사용 시간 12h / 60 min -> 0.00175 kWh/min. 0.00175kWh/min * 150원/kWh / (1500 원/$) -> 0.000175 $/min.
  env_cost_per_min: 0.00016 # Starship Technology 문서 + Kirschstein(2020) 논문 참고. 배터리 용량 1.26kWh / 사용 시간 12h / 60 min -> 0.00175 kWh/min. 0.00175kWh/min * CO2 배출량 0.0005 tCO2/kWh -> 0.000000875 tCO2/min * 185 $/tCO2 -> 0.000161875 $/min.
  service_time_min: 1.0 # 유선님 논문(2025) 참고.
  unload_time_min: 1.0 # 유선님 논문(2025) 참고.
  load_time_min: 0.5 # 유선님 논문(2025) 참고.

lateness:
  cost_per_min: 0.083 # Ostermeier(2023) 논문 참고. 5유로/1시간 -> 0.0833.../min

demand_per_customer: 1

time_window:
  hours: 4.0
